id: A7D19B19F
title: A Prayer to the Precious Guru from Uḍḍiyāna That Spontaneously Fulfils All
  Wishes
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:12:54.159977
  last_modified_at: 2022-02-28 23:12:54.159985
